title: QueryNest
emoji: "ğŸªºğŸ”"
colorFrom: yellow
colorTo: yellow
sdk: docker
short_description: Privacy-first, AI-powered web search engine for your browser
pinned: true
custom_headers:
  cross-origin-embedder-policy: require-corp
  cross-origin-opener-policy: same-origin
  cross-origin-resource-policy: cross-origin
